<!-- Generated by adapters/render.sh from agents/{{SOURCE}}.md. Do not edit. -->
---
name: {{NAME}}
description: {{DESCRIPTION}}
tools: {{TOOLS}}
model: {{MODEL}}
---

{{BODY}}

Rationale (human facing, not loaded by tools): agents/{{SOURCE}}.rationale.md
