<!-- Generated by adapters/render.sh from agents/{{SOURCE}}.md. Do not edit. -->
---
name: {{NAME}}
description: {{DESCRIPTION}}
model: {{MODEL}}
readonly: {{READONLY}}
---

{{BODY}}

Rationale (human facing, not loaded by tools): agents/{{SOURCE}}.rationale.md
