#!/usr/bin/env bash
# adapters/render.sh
# Generate tool adapters from agents/*.md and eval/models.yaml.
# Adapters contain no logic. Running twice produces no diff.
# --check exits 1 when generated files differ from what would be written.
#
# By default both Claude and Cursor adapters are rendered. Pass one or more
# targets to render only those: adapters/render.sh cursor

set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../scripts/lib/version.sh
source "$HARNESS_ROOT/scripts/lib/version.sh"

usage() {
  cat <<'EOF'
Usage: adapters/render.sh [claude|cursor]...
       adapters/render.sh --check [claude|cursor]...
       adapters/render.sh -h|--help
       adapters/render.sh -v|--version

Renders canonical roles into tool-specific adapters. The only place a model
is chosen is eval/models.yaml. This script injects the resolved id.

With no targets, both claude and cursor are rendered. Pass one or more
targets when you only use that tool, so the other adapter tree is left alone.

--check  exit 1 when generated files for the selected targets would change (CI)
EOF
}

CHECK=0
harness_parse_flags --check -- "$@"
if [[ "${HARNESS_CLI_HELP}" -eq 1 ]]; then
  usage
  exit 0
fi
if [[ "${HARNESS_CLI_VERSION}" -eq 1 ]]; then
  harness_print_version_and_exit
fi
if [[ ${#HARNESS_CLI_ACTIONS[@]} -gt 0 ]]; then
  CHECK=1
fi

RENDER_CLAUDE=0
RENDER_CURSOR=0
if [[ ${#HARNESS_CLI_POSITIONAL[@]} -eq 0 ]]; then
  RENDER_CLAUDE=1
  RENDER_CURSOR=1
else
  for target in "${HARNESS_CLI_POSITIONAL[@]}"; do
    case "$target" in
      claude) RENDER_CLAUDE=1 ;;
      cursor) RENDER_CURSOR=1 ;;
      *)
        echo "unrecognised target: ${target}" >&2
        echo "valid: claude cursor" >&2
        exit 2
        ;;
    esac
  done
fi

harness_need_cmd jq
harness_need_cmd yq
harness_need_cmd git

MODELS="$HARNESS_ROOT/eval/models.yaml"
AGENTS_DIR="$HARNESS_ROOT/agents"
TPL_DIR="$HARNESS_ROOT/adapters/templates"
STALE=0

_harness_frontmatter_json() {
  awk 'BEGIN{p=0} /^---[[:space:]]*$/{c++; if(c==1){p=1; next} if(c==2){exit}} p' "$1" | yq -o json '.'
}

_harness_body() {
  awk 'BEGIN{p=0} /^---[[:space:]]*$/{c++; if(c==2){p=1; next}} p' "$1" | sed -e '1{/^$/d;}'
}

_harness_render_tpl() {
  local tpl=$1
  jq -n -r \
    --arg name "$2" \
    --arg description "$3" \
    --arg model "$4" \
    --arg tools "$5" \
    --arg body "$6" \
    --arg source "$7" \
    --arg readonly "$8" \
    --rawfile tpl "$tpl" '
      $tpl
      | gsub("\\{\\{NAME\\}\\}"; $name)
      | gsub("\\{\\{DESCRIPTION\\}\\}"; $description)
      | gsub("\\{\\{MODEL\\}\\}"; $model)
      | gsub("\\{\\{TOOLS\\}\\}"; $tools)
      | gsub("\\{\\{BODY\\}\\}"; $body)
      | gsub("\\{\\{SOURCE\\}\\}"; $source)
      | gsub("\\{\\{READONLY\\}\\}"; $readonly)
    '
}

_harness_write() {
  local dest=$1
  local content=$2
  mkdir -p "$(dirname "$dest")"
  if [[ -f "$dest" ]] && printf '%s' "$content" | cmp -s - "$dest"; then
    return 0
  fi
  if [[ "$CHECK" -eq 1 ]]; then
    echo "stale: ${dest#$HARNESS_ROOT/}" >&2
    STALE=1
    return 0
  fi
  printf '%s' "$content" > "$dest"
}

_harness_write_json() {
  local dest=$1
  local json=$2
  local pretty
  pretty="$(jq -S '.' <<<"$json")"$'\n'
  _harness_write "$dest" "$pretty"
}

# Cursor JSONC: a comment is required in the generated file so failClosed is
# explained next to the field it qualifies. Cursor accepts the comment.
_harness_write_cursor_hooks() {
  local dest=$1
  local json=$2
  local pretty body
  pretty="$(jq -S '.' <<<"$json")"
  body="$(cat <<EOF
// Generated by adapters/render.sh. Do not edit.
// failClosed is true on preToolUse and stop because Cursor fails open on
// unexpected non-zero exits. A crashing hook that silently stops protecting
// you is the quietest failure mode in this system.
${pretty}
EOF
)"
  _harness_write "$dest" "${body}"$'\n'
}

render_claude_hooks() {
  local settings
  settings="$(jq -n \
    --arg s 'env HARNESS_TOOL=claude HARNESS_EVENT=session_start ./scripts/hook.sh' \
    --arg pre 'env HARNESS_TOOL=claude HARNESS_EVENT=pre_tool ./scripts/hook.sh' \
    --arg post 'env HARNESS_TOOL=claude HARNESS_EVENT=post_tool ./scripts/hook.sh' \
    --arg stop 'env HARNESS_TOOL=claude HARNESS_EVENT=stop ./scripts/hook.sh' \
    '{
    hooks: {
      SessionStart: [ { hooks: [ { type: "command", command: $s } ] } ],
      PreToolUse:   [ { hooks: [ { type: "command", command: $pre } ] } ],
      PostToolUse:  [ { hooks: [ { type: "command", command: $post } ] } ],
      Stop:         [ { hooks: [ { type: "command", command: $stop } ] } ]
    }
  }')"
  _harness_write_json "$HARNESS_ROOT/.claude/settings.json" "$settings"
}

render_cursor_hooks() {
  local hooks
  hooks="$(jq -n \
    --arg s 'env HARNESS_TOOL=cursor HARNESS_EVENT=session_start ./scripts/hook.sh' \
    --arg pre 'env HARNESS_TOOL=cursor HARNESS_EVENT=pre_tool ./scripts/hook.sh' \
    --arg post 'env HARNESS_TOOL=cursor HARNESS_EVENT=post_tool ./scripts/hook.sh' \
    --arg stop 'env HARNESS_TOOL=cursor HARNESS_EVENT=stop ./scripts/hook.sh' \
    '{
    version: 1,
    hooks: {
      sessionStart: [ { command: $s } ],
      preToolUse:   [ { command: $pre, failClosed: true } ],
      postToolUse:  [ { command: $post } ],
      stop:         [ { command: $stop, failClosed: true } ]
    }
  }')"
  _harness_write_cursor_hooks "$HARNESS_ROOT/.cursor/hooks.json" "$hooks"
}

if [[ "$RENDER_CLAUDE" -eq 1 ]]; then
  render_claude_hooks
fi
if [[ "$RENDER_CURSOR" -eq 1 ]]; then
  render_cursor_hooks
fi

shopt -s nullglob
for src in "$AGENTS_DIR"/*.md; do
  base="$(basename "$src")"
  case "$base" in
    *.rationale.md) continue ;;
  esac
  name="${base%.md}"
  fm="$(_harness_frontmatter_json "$src")"
  tier="$(jq -r '.tier' <<<"$fm")"
  description="$(jq -r '.description' <<<"$fm")"
  tools="$(jq -r '.tools' <<<"$fm")"
  display_name="$(jq -r '.name' <<<"$fm")"
  body="$(_harness_body "$src")"
  model="$(yq -o json '.' "$MODELS" | jq -r --arg t "$tier" '.tiers[$t].id // empty')"
  if [[ -z "$model" ]]; then
    echo "render: no model id for tier '${tier}' (role ${name}). Check eval/models.yaml." >&2
    exit 2
  fi
  readonly="false"
  case "$tools" in
    *Write*|*Edit*) readonly="false" ;;
    *) readonly="true" ;;
  esac

  if [[ "$RENDER_CLAUDE" -eq 1 ]]; then
    claude_out="$(_harness_render_tpl "$TPL_DIR/claude-agent.md.tpl" "$display_name" "$description" "$model" "$tools" "$body" "$name" "$readonly")"
    _harness_write "$HARNESS_ROOT/.claude/agents/${name}.md" "$claude_out"
  fi
  if [[ "$RENDER_CURSOR" -eq 1 ]]; then
    cursor_out="$(_harness_render_tpl "$TPL_DIR/cursor-agent.md.tpl" "$display_name" "$description" "$model" "$tools" "$body" "$name" "$readonly")"
    _harness_write "$HARNESS_ROOT/.cursor/agents/${name}.md" "$cursor_out"
  fi
done

# Skills have one source. The Claude adapter is a symlink, not a copy.
if [[ "$RENDER_CLAUDE" -eq 1 ]]; then
  if [[ "$CHECK" -eq 1 ]]; then
    if [[ ! -L "$HARNESS_ROOT/.claude/skills" ]] || [[ "$(readlink "$HARNESS_ROOT/.claude/skills")" != "../skills" ]]; then
      echo "stale: .claude/skills (expected symlink to ../skills)" >&2
      STALE=1
    fi
  else
    rm -f "$HARNESS_ROOT/.claude/.gitkeep"
    mkdir -p "$HARNESS_ROOT/.claude"
    ln -sfn ../skills "$HARNESS_ROOT/.claude/skills"
  fi
fi

if [[ "$RENDER_CURSOR" -eq 1 && "$CHECK" -eq 0 ]]; then
  rm -f "$HARNESS_ROOT/.cursor/.gitkeep"
  mkdir -p "$HARNESS_ROOT/.cursor/agents"
fi

# Tool list from shared/tools/mcp.yaml. Names and URLs only.
render_mcp() {
  local src="$HARNESS_ROOT/shared/tools/mcp.yaml"
  [[ -f "$src" ]] || return 0
  local json
  json="$(yq -o json '.' "$src")"
  if [[ "$RENDER_CURSOR" -eq 1 ]]; then
    # Cursor MCP project config: mcpServers map. Verified shape against Cursor
    # docs pattern (url servers). No env secrets.
    local cursor_mcp
    cursor_mcp="$(jq -c '
      reduce .servers[] as $s ({mcpServers:{}};
        .mcpServers[$s.name] = {url: $s.url})
    ' <<<"$json")"
    _harness_write_json "$HARNESS_ROOT/.cursor/mcp.json" "$cursor_mcp"
  fi
  if [[ "$RENDER_CLAUDE" -eq 1 ]]; then
    # Claude Code project MCP file. Same constraint: URLs only.
    local claude_mcp
    claude_mcp="$(jq -c '
      reduce .servers[] as $s ({mcpServers:{}};
        .mcpServers[$s.name] = {type:"http", url: $s.url})
    ' <<<"$json")"
    _harness_write_json "$HARNESS_ROOT/.mcp.json" "$claude_mcp"
  fi
}
render_mcp

if [[ "$CHECK" -eq 1 && "$STALE" -eq 1 ]]; then
  exit 1
fi
exit 0
