import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { loadSensors } from '../checks/common.mjs';
import { formatAssignmentBlock, requireTool } from '../config.mjs';
import { computeTreeHash } from '../tree-hash.mjs';

/**
 * Session start orientation. Cannot refuse.
 */
export function sessionStart(root, config) {
  const log = spawnSync('git', ['log', '-5', '--oneline'], { cwd: root, encoding: 'utf8' });
  const handoffPath = path.join(root, 'HANDOFF.md');
  const handoff = fs.existsSync(handoffPath)
    ? fs.readFileSync(handoffPath, 'utf8').split('\n').slice(0, 40).join('\n')
    : '(no HANDOFF.md yet)';

  let acceptanceCount = 0;
  const specs = path.join(root, 'specs');
  if (fs.existsSync(specs)) {
    for (const slug of fs.readdirSync(specs)) {
      const acc = path.join(specs, slug, 'acceptance.json');
      if (!fs.existsSync(acc)) continue;
      const data = JSON.parse(fs.readFileSync(acc, 'utf8'));
      const entries = Array.isArray(data) ? data : data.entries || [];
      acceptanceCount += entries.filter((e) => e.passes).length;
    }
  }

  let sensors = [];
  try {
    sensors = loadSensors(root);
  } catch {
    sensors = [];
  }

  let tool = null;
  let toolError = null;
  try {
    tool = requireTool(config);
  } catch (e) {
    toolError = e.message;
  }

  const adapterFresh = checkAdapterFreshness(root, tool);

  return {
    treeHash: computeTreeHash(root),
    gitLog: log.stdout || '',
    handoffTail: handoff,
    acceptancePassing: acceptanceCount,
    sensors: sensors.map((s) => ({
      name: s.name,
      tier: s.tier,
      blocking: s.blocking,
      enabled: s.enabled !== false,
    })),
    assignment: formatAssignmentBlock(config),
    tool,
    toolError,
    adapterFresh,
  };
}

function checkAdapterFreshness(root, tool) {
  if (!tool) return { ok: false, detail: 'tool unset' };
  const marker = {
    cursor: path.join(root, '.cursor', 'hooks.json'),
    claude: path.join(root, '.claude', 'settings.json'),
    codex: path.join(root, '.codex', 'hooks.json'),
  }[tool];
  if (!marker || !fs.existsSync(marker)) {
    return { ok: false, detail: `adapter missing; run ./verify.sh --render` };
  }
  const text = fs.readFileSync(marker, 'utf8');
  if (!text.includes('GENERATED BY HARNESS') && !text.includes('harness-loop')) {
    return { ok: false, detail: 'adapter present but not harness-generated' };
  }
  return { ok: true, detail: 'adapter present' };
}
