import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { requireTool, resolveRoleBinding } from '../config.mjs';

const HEADER = `# GENERATED BY HARNESS (harness-loop-engineering). Do not edit.
# Re-run: ./verify.sh --render
`;

const THIS_DIR = path.dirname(fileURLToPath(import.meta.url));
const CURSOR_RENDER = path.resolve(THIS_DIR, '../../render/cursor');
const CLAUDE_RENDER = path.resolve(THIS_DIR, '../../render/claude');

/** Portable four events shared across tools. */
export const PORTABLE_EVENTS = Object.freeze([
  'sessionStart',
  'beforeShellExecution',
  'afterFileEdit',
  'stop',
]);

/**
 * Write adapter for the ONE tool in harness.local.yaml.
 */
export async function renderAdapter(root, config, { checkOnly = false } = {}) {
  const tool = requireTool(config);
  const outDirs = {
    cursor: path.join(root, '.cursor'),
    claude: path.join(root, '.claude'),
    codex: path.join(root, '.codex'),
  };

  // Mutual exclusive: remove other tool dirs when rendering
  if (!checkOnly) {
    for (const [name, d] of Object.entries(outDirs)) {
      if (name !== tool && fs.existsSync(d)) {
        fs.rmSync(d, { recursive: true, force: true });
      }
    }
  }

  const dir = outDirs[tool];
  const files = buildFiles(root, config, tool);
  const enable = config.hooks?.enable !== false;

  if (checkOnly) {
    for (const [rel, content] of Object.entries(files)) {
      if (content == null) continue;
      const abs = path.join(dir, rel);
      if (!fs.existsSync(abs)) {
        const err = new Error(`drift: missing ${path.relative(root, abs)}`);
        err.exitCode = 1;
        throw err;
      }
      if (typeof content === 'string') {
        const cur = fs.readFileSync(abs, 'utf8');
        if (normalize(cur) !== normalize(content)) {
          const err = new Error(`drift: ${path.relative(root, abs)} differs from render`);
          err.exitCode = 1;
          throw err;
        }
      }
    }
    return { ok: true, tool, events: listWiredEvents(tool, config) };
  }

  fs.mkdirSync(dir, { recursive: true });
  for (const [rel, content] of Object.entries(files)) {
    if (content == null) continue;
    const abs = path.join(dir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    if (typeof content === 'string') {
      fs.writeFileSync(abs, content);
      if (rel.endsWith('.mjs') || rel.endsWith('.sh')) fs.chmodSync(abs, 0o755);
    }
  }

  if (tool === 'cursor') {
    copyHookScripts(CURSOR_RENDER, dir);
  } else if (tool === 'claude') {
    copyHookScripts(CLAUDE_RENDER, dir);
    ensureClaudeMd(root);
  }

  const skillsSrc = path.join(root, 'harness', 'skills');
  const skillsDst = path.join(dir, 'skills');
  linkSkills(skillsSrc, skillsDst);

  for (const role of Object.keys(config.roles || {})) {
    if (config.roles[role]?.enabled === false) continue;
    let binding;
    try {
      binding = resolveRoleBinding(config, role);
    } catch {
      continue;
    }
    if (!binding) continue;
    const roleSrc = path.join(root, 'harness', 'roles', `${role}.md`);
    if (!fs.existsSync(roleSrc)) continue;
    const rendered = renderRoleForTool(tool, role, roleSrc, binding);
    fs.mkdirSync(path.join(dir, 'agents'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'agents', `${role}.md`), rendered);
  }

  const events = listWiredEvents(tool, config);
  console.error(`enforcement: ${enable ? 'on' : 'off'}`);
  for (const e of events) {
    console.error(`  ${e.event} → ${e.command}`);
  }
  if (tool === 'cursor') {
    console.error(
      'Note: for Cursor cloud agents, commit .cursor/hooks.json so enforcement follows the work off your machine.',
    );
    console.error('Recover wedged hooks: echo \'{"version":1,"hooks":{}}\' > .cursor/hooks.json && Reload Window');
  }

  return { ok: true, tool, dir, events };
}

export function listWiredEvents(tool, config) {
  const enable = config.hooks?.enable !== false;
  if (!enable) return [];
  if (tool === 'cursor') {
    const full = buildCursorHooksConfig(config);
    return Object.entries(full.hooks).map(([event, arr]) => ({
      event,
      command: arr[0]?.command,
    }));
  }
  if (tool === 'claude') {
    return [
      { event: 'SessionStart', command: 'bash hooks/session-start.sh' },
      { event: 'PreToolUse', command: 'bash hooks/pre-tool.sh' },
      { event: 'PostToolUse', command: 'bash hooks/post-tool.sh' },
      { event: 'Stop', command: 'bash hooks/stop.sh' },
    ];
  }
  return [
    { event: 'session_start', command: './verify.sh --hook' },
    { event: 'pre_tool', command: './verify.sh --hook' },
    { event: 'post_tool', command: './verify.sh --hook' },
    { event: 'stop', command: './verify.sh --hook' },
  ];
}

function copyHookScripts(renderRoot, destToolDir) {
  const srcDir = path.join(renderRoot, 'hooks');
  const dstDir = path.join(destToolDir, 'hooks');
  fs.mkdirSync(dstDir, { recursive: true });
  for (const name of fs.existsSync(dstDir) ? fs.readdirSync(dstDir) : []) {
    if (name.endsWith('.mjs')) fs.unlinkSync(path.join(dstDir, name));
  }
  if (!fs.existsSync(srcDir)) return;
  for (const name of fs.readdirSync(srcDir)) {
    if (!name.endsWith('.sh')) continue;
    const src = path.join(srcDir, name);
    const dst = path.join(dstDir, name);
    fs.copyFileSync(src, dst);
    fs.chmodSync(dst, 0o755);
  }
}

/**
 * Default Cursor adapter: portable four only (no beforeMCP).
 */
function buildCursorHooksConfig(config) {
  const fc = Boolean(config.hooks?.failClosed);
  return {
    version: 1,
    hooks: {
      sessionStart: [
        { command: 'bash hooks/session-start.sh', failClosed: false, timeout: 30 },
      ],
      beforeShellExecution: [
        { command: 'bash hooks/before-shell.sh', failClosed: fc, timeout: 15 },
      ],
      afterFileEdit: [
        { command: 'bash hooks/after-edit.sh', failClosed: false, timeout: 60 },
      ],
      stop: [
        {
          command: 'bash hooks/stop.sh',
          failClosed: false,
          timeout: 120,
          loop_limit: 5,
        },
      ],
    },
  };
}

function buildClaudeSettings(config) {
  const enable = config.hooks?.enable !== false;
  if (!enable) return { hooks: {} };
  const cmd = (script) => ({
    type: 'command',
    command: `bash hooks/${script}`,
  });
  return {
    hooks: {
      SessionStart: [cmd('session-start.sh')],
      PreToolUse: [cmd('pre-tool.sh')],
      PostToolUse: [cmd('post-tool.sh')],
      Stop: [cmd('stop.sh')],
    },
  };
}

function buildFiles(root, config, tool) {
  if (tool === 'cursor') {
    const enable = config.hooks?.enable !== false;
    const full = buildCursorHooksConfig(config);
    const disabled = { version: 1, hooks: {} };

    return {
      'hooks.json':
        HEADER.replace(/#/g, '//') +
        (enable
          ? `// hooks.enable=true failClosed=${Boolean(config.hooks?.failClosed)}\n` +
            '// Portable four: sessionStart | beforeShellExecution | afterFileEdit | stop\n' +
            '// beforeMCP is optional: harness/render/cursor/optional/before-mcp.sh\n' +
            '// Deny = exit 2. Recover: echo \'{"version":1,"hooks":{}}\' > .cursor/hooks.json\n'
          : '// hooks.enable is false. Set hooks.enable: true then --render.\n' +
            '// Recover: harness/render/cursor/HOOKS.md\n') +
        JSON.stringify(enable ? full : disabled, null, 2) +
        '\n',
      'hooks.env.md':
        `${HEADER}\n` +
        `Portable-four adapter. Thin scripts are bash → ./verify.sh.\n` +
        `Default hooks.enable: true. Recover: echo '{"version":1,"hooks":{}}' > .cursor/hooks.json\n`,
    };
  }

  if (tool === 'claude') {
    const settings = buildClaudeSettings(config);
    return {
      'settings.json':
        HEADER.replace(/#/g, '//') +
        '// Portable four: SessionStart | PreToolUse | PostToolUse | Stop\n' +
        JSON.stringify(settings, null, 2) +
        '\n',
    };
  }

  return {
    'hooks.json':
      HEADER +
      JSON.stringify(
        {
          session_start: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          pre_tool: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          post_tool: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          stop: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
        },
        null,
        2,
      ) +
      '\n',
  };
}

function ensureClaudeMd(root) {
  const p = path.join(root, 'CLAUDE.md');
  if (!fs.existsSync(p)) {
    fs.writeFileSync(p, '@AGENTS.md\n');
    return;
  }
  const cur = fs.readFileSync(p, 'utf8');
  if (cur.startsWith('@AGENTS.md')) return;
  fs.writeFileSync(p, '@AGENTS.md\n' + cur);
}

function renderRoleForTool(tool, role, roleSrc, binding) {
  const body = fs.readFileSync(roleSrc, 'utf8');
  return `${HEADER}\n# Role: ${role}\n# tier: ${binding.tier} → ${binding.modelId} (${binding.provider})\n# tool: ${tool}\n\n${body}`;
}

function linkSkills(src, dst) {
  try {
    if (fs.existsSync(dst)) {
      const st = fs.lstatSync(dst);
      if (st.isSymbolicLink()) fs.unlinkSync(dst);
      else return;
    }
    fs.symlinkSync(src, dst, 'dir');
  } catch {
    fs.cpSync(src, dst, { recursive: true });
  }
}

function normalize(s) {
  return s.replace(/\r\n/g, '\n').trim() + '\n';
}
