import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { requireTool, resolveRoleBinding } from '../config.mjs';

const HEADER = `# GENERATED BY HARNESS (harness-loop-engineering). Do not edit.
# Re-run: ./verify.sh --render
`;

const RENDER_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../render/cursor');

/**
 * Write adapter for the ONE tool in harness.local.yaml.
 */
export async function renderAdapter(root, config, { checkOnly = false } = {}) {
  const tool = requireTool(config);
  const outDirs = {
    cursor: path.join(root, '.cursor'),
    claude: path.join(root, '.claude'),
    codex: path.join(root, '.codex'),
  };

  const dir = outDirs[tool];
  const files = buildFiles(root, config, tool);

  if (checkOnly) {
    for (const [rel, content] of Object.entries(files)) {
      if (content == null) continue;
      const abs = path.join(dir, rel);
      if (!fs.existsSync(abs)) {
        const err = new Error(`drift: missing ${path.relative(root, abs)}`);
        err.exitCode = 1;
        throw err;
      }
      if (typeof content === 'string') {
        const cur = fs.readFileSync(abs, 'utf8');
        if (normalize(cur) !== normalize(content)) {
          const err = new Error(`drift: ${path.relative(root, abs)} differs from render`);
          err.exitCode = 1;
          throw err;
        }
      }
    }
    return { ok: true, tool };
  }

  fs.mkdirSync(dir, { recursive: true });
  for (const [rel, content] of Object.entries(files)) {
    if (content == null) continue;
    const abs = path.join(dir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    if (typeof content === 'string') {
      fs.writeFileSync(abs, content);
      if (rel.endsWith('.mjs') || rel.endsWith('.sh')) fs.chmodSync(abs, 0o755);
    }
  }

  if (tool === 'cursor') {
    copyCursorHookScripts(dir);
  }

  const skillsSrc = path.join(root, 'harness', 'skills');
  const skillsDst = path.join(dir, 'skills');
  linkSkills(skillsSrc, skillsDst);

  for (const role of Object.keys(config.roles || {})) {
    if (config.roles[role]?.enabled === false) continue;
    let binding;
    try {
      binding = resolveRoleBinding(config, role);
    } catch {
      continue;
    }
    if (!binding) continue;
    const roleSrc = path.join(root, 'harness', 'roles', `${role}.md`);
    if (!fs.existsSync(roleSrc)) continue;
    const rendered = renderRoleForTool(tool, role, roleSrc, binding);
    fs.mkdirSync(path.join(dir, 'agents'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'agents', `${role}.md`), rendered);
  }

  if (tool === 'cursor') {
    console.error(
      'Note: for Cursor cloud agents, commit .cursor/hooks.json so enforcement follows the work off your machine.',
    );
    if (config.hooks?.enable !== true) {
      console.error(
        'Cursor hooks are empty (hooks.enable: false). See harness/render/cursor/HOOKS.md to enable the split-event adapter.',
      );
    }
  }

  return { ok: true, tool, dir };
}

function copyCursorHookScripts(cursorDir) {
  const srcDir = path.join(RENDER_DIR, 'hooks');
  const dstDir = path.join(cursorDir, 'hooks');
  fs.mkdirSync(dstDir, { recursive: true });
  // Drop legacy node thin scripts if present
  for (const name of fs.existsSync(dstDir) ? fs.readdirSync(dstDir) : []) {
    if (name.endsWith('.mjs')) fs.unlinkSync(path.join(dstDir, name));
  }
  for (const name of fs.readdirSync(srcDir)) {
    if (!name.endsWith('.sh')) continue;
    const src = path.join(srcDir, name);
    const dst = path.join(dstDir, name);
    fs.copyFileSync(src, dst);
    fs.chmodSync(dst, 0o755);
  }
}

/**
 * Split-event Cursor adapter.
 * Thin scripts are bash → verify.sh only (no node in the adapter layer).
 * Paths relative to .cursor/hooks.json → `bash hooks/<script>.sh`
 */
function buildCursorHooksConfig(config) {
  const fc = Boolean(config.hooks?.failClosed);
  return {
    version: 1,
    hooks: {
      sessionStart: [
        { command: 'bash hooks/session-start.sh', failClosed: false, timeout: 30 },
      ],
      beforeShellExecution: [
        { command: 'bash hooks/before-shell.sh', failClosed: fc, timeout: 15 },
      ],
      beforeMCPExecution: [
        { command: 'bash hooks/before-mcp.sh', failClosed: fc, timeout: 15 },
      ],
      afterFileEdit: [
        { command: 'bash hooks/after-edit.sh', failClosed: false, timeout: 60 },
      ],
      stop: [
        {
          command: 'bash hooks/stop.sh',
          failClosed: false,
          timeout: 120,
          loop_limit: 5,
        },
      ],
    },
  };
}

function buildFiles(root, config, tool) {
  if (tool === 'cursor') {
    const enable = config.hooks?.enable === true;
    const full = buildCursorHooksConfig(config);
    const disabled = { version: 1, hooks: {} };

    return {
      'hooks.json':
        HEADER.replace(/#/g, '//') +
        (enable
          ? `// hooks.enable=true failClosed=${Boolean(config.hooks?.failClosed)}\n` +
            '// Split events: sessionStart | beforeShellExecution | beforeMCPExecution | afterFileEdit | stop\n' +
            '// Deny = exit 2 + permission deny. See harness/render/cursor/HOOKS.md\n'
          : '// hooks.enable is false (default). Set hooks.enable: true then --render.\n' +
            '// Scripts still copied to .cursor/hooks/ for fixture tests.\n' +
            '// Recovery: harness/render/cursor/HOOKS.md\n') +
        JSON.stringify(enable ? full : disabled, null, 2) +
        '\n',
      'hooks.full.example.json':
        HEADER.replace(/#/g, '//') +
        '// Copy into hooks.json after setting hooks.enable: true, or just enable + --render.\n' +
        JSON.stringify(full, null, 2) +
        '\n',
      'hooks.env.md':
        `${HEADER}\n` +
        `Split-event adapter. Thin scripts are bash → ./verify.sh (no Node in the adapter).\n` +
        `Command paths are relative to this .cursor/ directory.\n` +
        `Enable: hooks.enable: true in harness.local.yaml, then ./verify.sh --render\n` +
        `failClosed: only for beforeShellExecution / beforeMCPExecution when hooks.failClosed: true\n` +
        `Fixture test: node --test harness/lib/hooks/fixtures.test.mjs\n`,
    };
  }

  if (tool === 'claude') {
    const settings = {
      hooks: {
        SessionStart: [
          {
            type: 'command',
            command: 'HARNESS_TOOL=claude HARNESS_IN_HOOK=1 ./verify.sh --hook',
          },
        ],
        PreToolUse: [
          {
            type: 'command',
            command: 'HARNESS_TOOL=claude HARNESS_IN_HOOK=1 ./verify.sh --hook',
          },
        ],
        PostToolUse: [
          {
            type: 'command',
            command: 'HARNESS_TOOL=claude HARNESS_IN_HOOK=1 ./verify.sh --hook',
          },
        ],
        Stop: [
          {
            type: 'command',
            command: 'HARNESS_TOOL=claude HARNESS_IN_HOOK=1 ./verify.sh --hook',
          },
        ],
      },
    };
    return {
      'settings.json': HEADER.replace(/#/g, '//') + JSON.stringify(settings, null, 2) + '\n',
    };
  }

  return {
    'hooks.json':
      HEADER +
      JSON.stringify(
        {
          session_start: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          pre_tool: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          post_tool: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
          stop: 'HARNESS_TOOL=codex HARNESS_IN_HOOK=1 ./verify.sh --hook',
        },
        null,
        2,
      ) +
      '\n',
  };
}

function renderRoleForTool(tool, role, roleSrc, binding) {
  const body = fs.readFileSync(roleSrc, 'utf8');
  return `${HEADER}\n# Role: ${role}\n# tier: ${binding.tier} → ${binding.modelId} (${binding.provider})\n# tool: ${tool}\n\n${body}`;
}

function linkSkills(src, dst) {
  try {
    if (fs.existsSync(dst)) {
      const st = fs.lstatSync(dst);
      if (st.isSymbolicLink()) fs.unlinkSync(dst);
      else return;
    }
    fs.symlinkSync(src, dst, 'dir');
  } catch {
    fs.cpSync(src, dst, { recursive: true });
  }
}

function normalize(s) {
  return s.replace(/\r\n/g, '\n').trim() + '\n';
}
